services:
  - type: web
    name: gachaverse
    runtime: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SPIN_SECRET_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_GVCOIN_ADDRESS
        sync: false
      - key: GVCOIN_MINTER_PRIVATE_KEY
        sync: false
      - key: GVCOIN_RPC_URL
        value: https://ethereum-sepolia-rpc.publicnode.com
      - key: PORT
        value: 10000
